name: blog-box
author: Bryan Guner
description: GitHub Action for injecting your latest dev.to blog post into a gist

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: file-text
  color: green
